services:
  samba-ad:
    image: samba-ad:latest
    hostname: dc1
    container_name: samba-ad
    env_file:
      - .env
    cap_add:
      - SYS_NICE  # SYS_NICE — для приоритетов samba
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./local/data:/var/lib/samba
      - ./local/etc:/etc/samba
      - ./local:/out  # сюда пишется keytab
      - ./runtime/provision-objects.sh:/docker-entrypoint-init.d/10-provision-objects.sh:ro
      - ./local/domain-objects.conf:/docker-entrypoint-init.d/domain-objects.conf:ro
    ports:
      - "88:88"
      - "88:88/udp"
      - "464:464"
      - "464:464/udp"
      - "389:389"
      - "636:636"
      - "3268:3268"
      - "3269:3269"
    healthcheck:
      test: ["CMD-SHELL", "ss -tlnp | grep -q ':88 ' && ss -tlnp | grep -q ':389 ' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

networks:
  default:
    name: docker
    external: true
